name: magicthegathering_api_dart
description: Rest api wrapper for https://gatherer.wizards.com/Pages/Default.aspx.
version: 0.1.0
repository: https://github.com/Hecatoncheir/magicthegathering_api_dart

environment:
  sdk: ^3.2.6

dependencies:
  meta: ^1.11.0
  json_annotation: ^4.8.1
  http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  dart_code_metrics: ^5.7.6
  test: ^1.25.2
  build: ^2.4.1
  build_runner: ^2.4.8

dependency_overrides:
  http: ^1.2.0
